[build]
  functions = "backend/netlify/functions"
  publish = "backend/public"

[[redirects]]
  from = "/"
  to = "/signup.html"
  status = 302

[[redirects]]
  from = "/signup"
  to = "/.netlify/functions/api/signup"
  status = 200

[[redirects]]
  from = "/login"
  to = "/.netlify/functions/api/login"
  status = 200

[[redirects]]
  from = "/logout"
  to = "/.netlify/functions/api/logout"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200