[build]
  base = "backend"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/signup"
  to = "/.netlify/functions/api/signup"
  status = 200

[[redirects]]
  from = "/login"
  to = "/.netlify/functions/api/login"
  status = 200

[[redirects]]
  from = "/logout"
  to = "/.netlify/functions/api/logout"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200